### ISSUE TITLE
好像不能搭配flutter_staggered_grid_view一块使用

### ISSUE THREAD

**Issue by choykarl** [Vadaski/flutter_exposure#1]
flutter_staggered_grid_view是一个瀑布流的库，一起使用曝光的index不太准

**Comment by Vadaski** [comment]
我上传了一个 example，里面使用 flutter_staggered_grid_view 进行曝光实验，没有发现不准呢～ 你看看，如果有其他的 case 的话，能给一个可复现的 demo 最好了～

**Comment by choykarl** [comment]
> 我上传了一个 example，里面使用 flutter_staggered_grid_view 进行曝光实验，没有发现不准呢～ 你看看，如果有其他的 case 的话，能给一个可复现的 demo 最好了～

我们换方案😄
