### ISSUE TITLE
可以给出一个CustomScrollView的样例吗

### ISSUE THREAD

**Issue by champion0122** [Vadaski/flutter_exposure#2]

**Comment by Vadaski** [comment]
上传了一个 demo，我想了解下你的 case 里面是否存在变高的 widget，例如SliverAppBar 这样的呢？目前的计算方式和首次渲染拿到的 box 大小信息相关，如果有些 widget 高度变化，可能就计算不准确了。

**Comment by champion0122** [comment]
> 上传了一个 demo，我想了解下你的 case 里面是否存在变高的 widget，例如SliverAppBar 这样的呢？目前的计算方式和首次渲染拿到的 box 大小信息相关，如果有些 widget 高度变化，可能就计算不准确了。

确实是有SliverAppBar。
您的插件在我们项目上呈现的结果是——SliverList下面有9个渲染出来的Widget，但是统计曝光的一直只有三个，而且有两个是在View之外的。根据您的解答，我觉得应该是异步请求的数据在我们第一次渲染时还没加载完，所以第一次渲染的只有部分，然后导致统计的Widget不准确。感谢您的回答，我们现在用的另外一个插件。
祝好
