### ISSUE TITLE
在竖直方向的listview里面嵌套一个水平方向的listview，这个时候水平方向的曝光可能有问题

### ISSUE THREAD

**Issue by Passer-by** [Vadaski/flutter_exposure#6]
ScrollDetailProvider包裹在竖直方向的listview外面。

**Comment by Passer-by** [comment]
我在想要不要竖直方向的listview的item创建一个group 来包裹嵌套的listview。 这样每次先通知这个group。再由group判断自己是否可见，然后再遍历到嵌套的listview的item下面去

**Comment by Vadaski** [comment]
我理解这个需要包两个 ScrollDetailProvider，竖直和水平都需要
